cat version: '3'
services:
  ssr-api:
    image: ssr-api:latest
    restart: always
    expose:
      - "9001"
      - "3306"
      - "1521"
    ports:
      - "9001:9001"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
    
#      PLATFORM: "DEV"
#      LOG_LEVEL: 10
#      HOST: "host.docker.internal"
#      PORT: 3306
#      DATABASE: "SSR"
#      USER: "casops"
#      PASSWORD: "copsaretops"

#      PLATFORM: "PROD"
#      LOG_LEVEL: 10
#      HOST: "10.14.64.109"
#      PORT: 1521
#      DATABASE: "SSR"
#      USER: "system"
#      PASSWORD: "up580ard"

      PLATFORM: "NPD"
      LOG_LEVEL: 10
      HOST: "10.233.160.135"
      PORT: 1521
      DATABASE: "SSR"
      USER: "system"
      PASSWORD: "t3chn0l0gy"


    healthcheck:
       #test: ["CMD", "curl", "-X", "POST", "http://apiusername:apipassword@localhost:5000/api", "-o", "/dev/null"]
       interval: 60s
       timeout: 1s
       retries: 3
    logging:
      options:
        max-size: "10m"
